CSS-layout-classes - Aaron Butnik
aaron-j-butnik/c1022-code-solutions pull request #17
Opened 2022-10-13 18:31 UTC by aaron-j-butnik

![SSB-exercise](https://user-images.githubusercontent.com/103544497/195677687-67e7037c-478b-4f5f-9136-df13ad00317e.png)
![SSB-exercise-cont](https://user-images.githubusercontent.com/103544497/195677703-40027972-072e-43c8-b4a2-e53057abb428.png)

2022-10-13 21:37 UTC, codingcodymiller requested changes

2022-10-13 21:37 UTC, codingcodymiller commented on css-layout-classes/styles.css
> +.column-one-fouth {
`fourth`

2022-10-13 23:54 UTC, aaron-j-butnik commented
![css-layout-classes-correction](https://user-images.githubusercontent.com/103544497/195732209-b8e00205-3627-4535-a8a8-1e8a1d668e84.png)
![css-layout-classes-correction-2](https://user-images.githubusercontent.com/103544497/195732223-302494ef-9189-4648-b314-439117052784.png)

2022-10-14 20:50 UTC, codingcodymiller approved these changes

2022-10-14 21:56 UTC, merged