String manipulation 2 - Aaron Butnik
aaron-j-butnik/c1022-code-solutions pull request #55
Opened 2022-10-30 08:03 UTC by aaron-j-butnik

<img width="716" alt="String-manipulation-2" src="https://user-images.githubusercontent.com/103544497/198868564-adf4bbee-08d2-4ed9-a756-3ba64855ecd8.png">

2022-10-31 16:19 UTC, codingcodymiller requested changes

2022-10-31 16:19 UTC, codingcodymiller commented on string-manipulation-2/src/capitalize-word.js
> +    return word[0].toUpperCase() + word.slice(1, 4).toLowerCase() + word[4].toUpperCase() + word.slice(5).toLowerCase();
This is a very specific case where you know exactly what you want to return, so you don't need to assemble it programmatically. You can just `return "JavaScript";`

2022-10-31 16:19 UTC, codingcodymiller commented on string-manipulation-2/src/first-chars.js
> +      return string;
I would do this conditional before the loop begins, so you only need to do it once, rather than on every iteration of the loop.

2022-10-31 16:19 UTC, codingcodymiller commented on string-manipulation-2/src/last-chars.js
> +      return string;
I would do this conditional before the loop begins, so you only need to do it once, rather than on every iteration of the loop.

2022-11-05 20:07 UTC, aaron-j-butnik commented
<img width="716" alt="String-manipulation-2 png-fix-one" src="https://user-images.githubusercontent.com/103544497/200138988-8648d959-1322-4a18-a287-10ddda9ae186.png">
<img width="716" alt="String-manipulation-2 png-fix-two" src="https://user-images.githubusercontent.com/103544497/200138991-75a26043-8bd1-4703-b02c-e7f54d927f0e.png">
<img width="716" alt="String-manipulation-2 png-fix-three" src="https://user-images.githubusercontent.com/103544497/200138992-dc5c4097-653d-464f-9220-6ff860899a63.png">

2022-11-07 19:26 UTC, codingcodymiller approved these changes

2022-11-07 19:27 UTC, merged