Completed javascript-timers exercise - Aaron Butnik
aaron-j-butnik/c1022-code-solutions pull request #63
Opened 2022-11-09 18:29 UTC by aaron-j-butnik

![javascript-timer-1](https://user-images.githubusercontent.com/103544497/200911703-6b7fe0d0-358f-4c4b-a69f-d656ed904a67.gif)
![javascript-timer-3](https://user-images.githubusercontent.com/103544497/200911722-39a9bc55-9d58-429f-8798-fd7ab09271fb.gif)

2022-11-09 19:50 UTC, codingcodymiller requested changes

2022-11-09 19:50 UTC, codingcodymiller commented on javascript-timers/interval.js
> +  } else if ($countdown.textContent === '1') {
This will work, but it is very manual. What if the timer needed to start at 1000? That would be a lot of conditional blocks 😬

2022-11-10 08:14 UTC, aaron-j-butnik commented
![image](https://user-images.githubusercontent.com/103544497/201036959-9da04e8e-2abc-40bc-81cc-9f790d10be6e.png)

2022-11-10 19:52 UTC, codingcodymiller approved these changes

2022-11-10 23:37 UTC, merged