Array manipulation 3 - Aaron Butnik
aaron-j-butnik/c1022-code-solutions pull request #79
Opened 2022-12-01 08:25 UTC by aaron-j-butnik

![Array-manipulation-3](https://user-images.githubusercontent.com/103544497/205002885-f628757b-eb5f-46d2-b8e2-61d946df5c51.png)

2022-12-01 18:53 UTC, thebearingedge requested changes

2022-12-01 18:53 UTC, thebearingedge commented on array-manipulation-3/src/equal.js
> +  });
The length check at the beginning is good, but after that we need to compare the array elements directly to each other at each index. Try looping through the first array and comparing each element to the second array "at" the same index.

2022-12-01 22:57 UTC, aaron-j-butnik commented on array-manipulation-3/src/equal.js
> +  });
Ah ok I see.

2022-12-01 23:47 UTC, aaron-j-butnik commented
![image](https://user-images.githubusercontent.com/103544497/205182870-635e58ad-b221-431f-afea-49427f28355c.png)

2022-12-02 00:34 UTC, thebearingedge approved these changes

2022-12-02 00:46 UTC, merged